language: go
go:
- 1.2
before_install:
- git submodule update --init --recursive
branches:
  only:
  - master
source_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBcFV3VFlQai9hTUN1a2piY0hNbE05ZmdOTXpiT2xvTk5FVHhIRXRtbkhXZFhNM1RnCnhQYmdPU2x4YzkyNFFFNlp1SXZKWlhrNHc0QVdEWlpIMEQzR21Md1hqZzdnQ0NENWN6UFhzQ09JazBSZTN1cDQKRVcybHdmUTFqdFVKME44OHhBWkRqRFdCWkRvK0M2cGluUmI5R0VHbXBkWXlYbjFNS1UwY0NwN1hEMzA1Wm9LaQpTaDEzSTRtZVB6K0luMzZYcFR2WW9DSFNYSzh1UnF3RHpEWWFFbXlOQ1A0alRzSDlnOHk0WmhEL1VlR1lPV25vCjN0RDNHclNRMEhRby9SYVNIbUJWZXI2aWg1MEhjTS82c0hXMlNaNzE2VWFNTzR2ajVRL3E2ejB0cnpUVnJRTFkKQUF2bTZYZWlISmRsRWIwYmN5bkVzU0k5TjZpSXVLUFhEampkV3dJREFRQUJBb0lCQUhZbHNUZy80WGNET2dQaQpXR1B1OGlaaFhUWDg5NTZYVE8rRDBSMUZHdkNtVzZxNDRLdUg5ZTZGazhVSWRsam9sWEZWNE9hNXhYdmZRbVFGCnhXQ3Z0eEtXWnBPd1NDc25Qb1U4U2U5cEJvYVVlT2NHV2puQzBKYVlNZXZjay82S2dZbHZITHJMeDZkWEJlQWEKc2crc1RjMFhwOENqSUM5dmlZOS93UXBLVEZlUnVQTU5scDVsSjRwdDRCRnJwM2tqRWdoNzJCbXFNaWpEb2hBYwppZXBzMmY3Y3lTMlgrYWJtWEhkTjl5a2Q0TUIwRHlzY3hCanI1bWNTREJTTndJdFRSb1VOd2dZRUVZdjNsVzJHCnFQZFhtUVlnNXVhU3VEcno0MzVNOHhLNkNxNGtmL3NIN1cwOXd4Ulh4VGV3M2ZaZm9oYmFZbndNS0ducHhxYkYKSHIrdEF3a0NnWUVBemVLdHNHY0J6THEyRWNaaTFSbTJFakxEVEV1SE02M2o5YWgvOERIZ1A0NEJTbmpyVm9JcQo5YUlHdjU1L1pBb3U5K3phSGRFZVBYM21YbGhzNndHS2Y0RTdGTGg3aHYyd2Zab2VrVldNYnNpWUFTNi9RdTQ1CmM4djh5UHVFN3paZHlsWHBrL2xEMU5yWnpCaytwanUzZnBhOFJGVjU5SEh1cHlCU0RERUc3SlVDZ1lFQXpZZzUKQ0twbCtYZ291QkllMUVFR08xcXdCcnYxS1JqQWF1ellEUktEYmc4bE5zekY1N3RRbUZTemhsQTNqelllSUVTZwpkSHV1dlQ4NElDc2xqUU14bXRuRE1zZkswdXMyVzcxL28zV3RFWlpSeUpGODUxNndlUW1xa3FxQ2Jzc0ovL2hSCmp4RDlQbTFvcmdHYnVpZ1h6eEpISStpZFAyNmpwdGV5K0NqY05pOENnWUVBeHBKdnBTamtVbnB1YWx4bUxGUjkKQjdaUUtNRGI2TnM1ZDFFSi9EZU9xcDJpM3hvYkdUZTRpV3E1aVkwc0h1ZTNmMFhBNVdzdytHdjZpVnBOeXFlVQoxZjlsWlVtOVVtaFNGZ0pVb3lYWXFXenRObzdJeDV3T2E0SCtFRGFPYzAyRFRraG9YV0RYckc5Y0N2NzZMc2gvCjVTY3E4OWxoSTRQVGd2dW9ScnZ1aXJVQ2dZRUFpTkhVL2NMSkxYL2l3MTQwcmFFM3I4MVgvck9pcVIvei8zbjQKL1FMRkFVQU55dVFZSG9JZ1RiZWM1cDJCenREOHp3aEFOQ3Fka1JlRG1rNStxZGRsYnlybGVXbHN5R21SL3hJdgo1TFdTWjNIRXNackFKaGx2cXJOWG5GanJpU3VhVlk2TlpJcXZ1cDRFb0VrcnpJbWlCOU9vRGV4c3VXeENmdTk2CkVSN0tNVHNDZ1lFQXBxOXhoWEJGK1NFNjRXbGF2RkFxM21VVHlMR1k4Tlc1aUxDemdlTTdhQXJMSXk4eXZIUWgKd1NZQ1U0UDc5MVVLVlIrTGNuRWdYWXErWXhXemRKWU0xdjk3eWlJQnA2V1NzZEc2Q1lVQjR1K1BDZlJFZ3JKdgpoVWdEakhiM25UbWlJNFAzQXc2a1R3T0N0Z1cvck9XL1FvSXpsUGpydzdFYmhwMStvVmE5dHdRPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
install:
- echo "trying to avoid travis ci from attempting to get all packages from the internet"
env:
  matrix:
  - TEST_DB=database_${TRAVIS_BUILD_ID}_${RANDOM}
  global:
  - secure: yFy4F0LMFqBHMABLkFdBUezq+JoTynk5kgcelgscgcN5PsCKES1NvbkLHTaJZMb836Lb2uSgqL0g+3Z6s+KtsWb8Vi4AIDKafQfMa4bqKBRkUA8ObXkKFWvZEw5OCvYf6iReUCNsH7mQJjp0G+YCGO0pI0DRkm+nJRQW4r3mhiQ=
  - secure: mgpF9qjjTQ0mu8PXo1rqOUyY08Ik1GqEvzUmFk/eL7RmnvssyVlEhyzzlwcdSaavwU9QMe/1LCZ5VaV5g6QvnbAiu0nUh4UDoafwXqHjB3Y+75RHMu6dWDs1E+7K08JOczDW4OZdrPRIOJrCHsqVOIcV8u/huShfxDHvrdtzfTk=
  - secure: Ip8X+IWnKmU+523CFjPVJRYul0+ezbsI3zMh/SzT/iCJyJ4Pw/5gdsY9LhtZl+p/nLQJlehn/FwmWo8NjV3SdZ7QGtBvaUEmLPkeKGVTpcyEjFz6XKtoRXxCWhvnphXUFZaU8HjqAv78fD/G2+EcmInfCoBg7fK8FKk1TeWmqWA=
  - secure: ZjeraleiMdr/wmH74vAU5ruL+CdzbGyImwXWLz6ZsUDD0dbK+oMFe1WmNJOsO1yeW/WGXD1enemzDeBrdVqDFXClyzbHcVtZ86YZSgYjtadocEX+RslbobrfNWxW8w/KHioObC7wpyBllQQb8hqzS1rakFOjZ7t0CgpNUiuBsLE=
  - secure: GAHw/Z037AezGOA5v/j1MvZTdLL/RFcofSdgH2mfp+nQWvswbQRS5dxJyfJO6BcNkZrvnuru3Lnh7azKShw6XUD+RT+vq0Ata5KQ4BiZa+ssX3VnMIsvrM4VIPxh+v6ESRPYvym1GHUKc7tqJ+ObVXaTkPJH8vqbdx7JHXSNjCM=
  - secure: Sown1iottx8PNGM8qEXH/txfPXYZr+wp+fcXueCoZns/5zmoUTGILOj04IBcuz0MDGPWpb8CddpIIbh7SjCTWLhY9kL3RJCxdi7vat9t2aat2mmpodIT8CjEAoWEW555aXUtWcUoIPsi0MNbRCL7mJnSwpFtx9oCIe4qv5fQksM=
  - secure: gzt5DC2qHXU3gsMDOnGeiQfIV6Ao+gQKQ5v2fhDYYfdKNgEFYXRL7jGqpa5+Qg/cadz9Q5R39KB5ywXrpVJTri95IZJxIsU2Q6/D84IhOIl8Jm8FQFG042yLjT1eP/xlVZyixsI7RbG95xss4I1TLy/dlUOxA1uYcI1y3YGsAwM=
  - secure: Xu2RGDZcWL3YGUto8OI2FLaFq9iVT9yMAwuge3wDrhXeNVRj0+ZNDO1dqrfjIPp7z4072INzwZKXKvTLS2CrIDmkRo1i6S62fYCoUm33tcKEoBHNFrmy5yDuJgX8yNOlBEnVoDKbE4tmPdCGkOAsW/Dj0KTZik1me7dLcTMtEUA=
script:
- export GOPATH=$(pwd)
- export CAREFRONT_PROJECT_DIR=$(pwd)
- go build ./src/carefront/...
- go fmt ./src/carefront/...
- go get code.google.com/p/go.tools/cmd/vet
- go get code.google.com/p/go.tools/cmd/cover
- go vet ./src/carefront/...
- go test -i -race ./src/carefront/...
- go test -v -race -cover -test.timeout=50m ./src/carefront/... 
notifications:
  # webhooks:
  #   urls:
  #   - https://carefront.slack.com/services/hooks/travis?token=Ca0yGyN1ZKPBFL4T6NNjegiX
  #   on_success: change
  #   on_failure: always
  #   on_start: false
  email:
  - backend@carefront.net
