language: go
go:
  - tip

before_install:
  - git submodule update --init --recursive

branches:
  only:
    - master

source_key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBcFV3VFlQai9hTUN1a2piY0hNbE05ZmdOTXpiT2xvTk5FVHhIRXRtbkhXZFhNM1RnCnhQYmdPU2x4YzkyNFFFNlp1SXZKWlhrNHc0QVdEWlpIMEQzR21Md1hqZzdnQ0NENWN6UFhzQ09JazBSZTN1cDQKRVcybHdmUTFqdFVKME44OHhBWkRqRFdCWkRvK0M2cGluUmI5R0VHbXBkWXlYbjFNS1UwY0NwN1hEMzA1Wm9LaQpTaDEzSTRtZVB6K0luMzZYcFR2WW9DSFNYSzh1UnF3RHpEWWFFbXlOQ1A0alRzSDlnOHk0WmhEL1VlR1lPV25vCjN0RDNHclNRMEhRby9SYVNIbUJWZXI2aWg1MEhjTS82c0hXMlNaNzE2VWFNTzR2ajVRL3E2ejB0cnpUVnJRTFkKQUF2bTZYZWlISmRsRWIwYmN5bkVzU0k5TjZpSXVLUFhEampkV3dJREFRQUJBb0lCQUhZbHNUZy80WGNET2dQaQpXR1B1OGlaaFhUWDg5NTZYVE8rRDBSMUZHdkNtVzZxNDRLdUg5ZTZGazhVSWRsam9sWEZWNE9hNXhYdmZRbVFGCnhXQ3Z0eEtXWnBPd1NDc25Qb1U4U2U5cEJvYVVlT2NHV2puQzBKYVlNZXZjay82S2dZbHZITHJMeDZkWEJlQWEKc2crc1RjMFhwOENqSUM5dmlZOS93UXBLVEZlUnVQTU5scDVsSjRwdDRCRnJwM2tqRWdoNzJCbXFNaWpEb2hBYwppZXBzMmY3Y3lTMlgrYWJtWEhkTjl5a2Q0TUIwRHlzY3hCanI1bWNTREJTTndJdFRSb1VOd2dZRUVZdjNsVzJHCnFQZFhtUVlnNXVhU3VEcno0MzVNOHhLNkNxNGtmL3NIN1cwOXd4Ulh4VGV3M2ZaZm9oYmFZbndNS0ducHhxYkYKSHIrdEF3a0NnWUVBemVLdHNHY0J6THEyRWNaaTFSbTJFakxEVEV1SE02M2o5YWgvOERIZ1A0NEJTbmpyVm9JcQo5YUlHdjU1L1pBb3U5K3phSGRFZVBYM21YbGhzNndHS2Y0RTdGTGg3aHYyd2Zab2VrVldNYnNpWUFTNi9RdTQ1CmM4djh5UHVFN3paZHlsWHBrL2xEMU5yWnpCaytwanUzZnBhOFJGVjU5SEh1cHlCU0RERUc3SlVDZ1lFQXpZZzUKQ0twbCtYZ291QkllMUVFR08xcXdCcnYxS1JqQWF1ellEUktEYmc4bE5zekY1N3RRbUZTemhsQTNqelllSUVTZwpkSHV1dlQ4NElDc2xqUU14bXRuRE1zZkswdXMyVzcxL28zV3RFWlpSeUpGODUxNndlUW1xa3FxQ2Jzc0ovL2hSCmp4RDlQbTFvcmdHYnVpZ1h6eEpISStpZFAyNmpwdGV5K0NqY05pOENnWUVBeHBKdnBTamtVbnB1YWx4bUxGUjkKQjdaUUtNRGI2TnM1ZDFFSi9EZU9xcDJpM3hvYkdUZTRpV3E1aVkwc0h1ZTNmMFhBNVdzdytHdjZpVnBOeXFlVQoxZjlsWlVtOVVtaFNGZ0pVb3lYWXFXenRObzdJeDV3T2E0SCtFRGFPYzAyRFRraG9YV0RYckc5Y0N2NzZMc2gvCjVTY3E4OWxoSTRQVGd2dW9ScnZ1aXJVQ2dZRUFpTkhVL2NMSkxYL2l3MTQwcmFFM3I4MVgvck9pcVIvei8zbjQKL1FMRkFVQU55dVFZSG9JZ1RiZWM1cDJCenREOHp3aEFOQ3Fka1JlRG1rNStxZGRsYnlybGVXbHN5R21SL3hJdgo1TFdTWjNIRXNackFKaGx2cXJOWG5GanJpU3VhVlk2TlpJcXZ1cDRFb0VrcnpJbWlCOU9vRGV4c3VXeENmdTk2CkVSN0tNVHNDZ1lFQXBxOXhoWEJGK1NFNjRXbGF2RkFxM21VVHlMR1k4Tlc1aUxDemdlTTdhQXJMSXk4eXZIUWgKd1NZQ1U0UDc5MVVLVlIrTGNuRWdYWXErWXhXemRKWU0xdjk3eWlJQnA2V1NzZEc2Q1lVQjR1K1BDZlJFZ3JKdgpoVWdEakhiM25UbWlJNFAzQXc2a1R3T0N0Z1cvck9XL1FvSXpsUGpydzdFYmhwMStvVmE5dHdRPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="

install: 
  - echo "trying to avoid travis ci from attempting to get all packages from the internet" 

env:
  - RDS_INSTANCE="dev-db-3.ccvrwjdx3gvp.us-east-1.rds.amazonaws.com" RDS_USERNAME="carefront" RDS_PASSWORD="changethis" TEST_DB=database_$TRAVIS_BUILD_ID AWS_ACCESS_KEY=AKIAJ7Q3EZR5EWJKJLMA AWS_SECRET_KEY=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

before_script:
  - pushd src/carefront/mysql/
  - latestSnapshotNumber=`ls -r snapshot-*.sql | cut -d- -f 2  | cut -d. -f1 | sort -nr | head -1`
  - latestDataSnapshotNumber=`ls -r data-snapshot-*.sql | cut -d- -f 3  | cut -d. -f1 | sort -nr | head -1`
  - echo "create database $TEST_DB; use $TEST_DB;"  | cat - snapshot-$latestSnapshotNumber.sql > current.sql
  - echo "use $TEST_DB;" | cat - data-snapshot-$latestDataSnapshotNumber.sql > current_data.sql
  - mysql -h $RDS_INSTANCE -u $RDS_USERNAME -p$RDS_PASSWORD < current.sql
  - mysql -h $RDS_INSTANCE -u $RDS_USERNAME -p$RDS_PASSWORD < current_data.sql
  - popd 

script:
  - export GOPATH=$(pwd)
  - go build ./src/carefront/...
  - go fmt ./src/carefront/...
  - go get code.google.com/p/go.tools/cmd/vet
  - go vet ./src/carefront/...
  - go test -i -race ./src/carefront/...
  - go test -v -race ./src/carefront/...

after_script:
  - echo "drop database $TEST_DB;" > drop_database.sql
  - mysql -h $RDS_INSTANCE -u $RDS_USERNAME -p$RDS_PASSWORD < drop_database.sql
