language: go
go:
- 1.4
before_install:
- git submodule update --init --recursive
source_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBcFV3VFlQai9hTUN1a2piY0hNbE05ZmdOTXpiT2xvTk5FVHhIRXRtbkhXZFhNM1RnCnhQYmdPU2x4YzkyNFFFNlp1SXZKWlhrNHc0QVdEWlpIMEQzR21Md1hqZzdnQ0NENWN6UFhzQ09JazBSZTN1cDQKRVcybHdmUTFqdFVKME44OHhBWkRqRFdCWkRvK0M2cGluUmI5R0VHbXBkWXlYbjFNS1UwY0NwN1hEMzA1Wm9LaQpTaDEzSTRtZVB6K0luMzZYcFR2WW9DSFNYSzh1UnF3RHpEWWFFbXlOQ1A0alRzSDlnOHk0WmhEL1VlR1lPV25vCjN0RDNHclNRMEhRby9SYVNIbUJWZXI2aWg1MEhjTS82c0hXMlNaNzE2VWFNTzR2ajVRL3E2ejB0cnpUVnJRTFkKQUF2bTZYZWlISmRsRWIwYmN5bkVzU0k5TjZpSXVLUFhEampkV3dJREFRQUJBb0lCQUhZbHNUZy80WGNET2dQaQpXR1B1OGlaaFhUWDg5NTZYVE8rRDBSMUZHdkNtVzZxNDRLdUg5ZTZGazhVSWRsam9sWEZWNE9hNXhYdmZRbVFGCnhXQ3Z0eEtXWnBPd1NDc25Qb1U4U2U5cEJvYVVlT2NHV2puQzBKYVlNZXZjay82S2dZbHZITHJMeDZkWEJlQWEKc2crc1RjMFhwOENqSUM5dmlZOS93UXBLVEZlUnVQTU5scDVsSjRwdDRCRnJwM2tqRWdoNzJCbXFNaWpEb2hBYwppZXBzMmY3Y3lTMlgrYWJtWEhkTjl5a2Q0TUIwRHlzY3hCanI1bWNTREJTTndJdFRSb1VOd2dZRUVZdjNsVzJHCnFQZFhtUVlnNXVhU3VEcno0MzVNOHhLNkNxNGtmL3NIN1cwOXd4Ulh4VGV3M2ZaZm9oYmFZbndNS0ducHhxYkYKSHIrdEF3a0NnWUVBemVLdHNHY0J6THEyRWNaaTFSbTJFakxEVEV1SE02M2o5YWgvOERIZ1A0NEJTbmpyVm9JcQo5YUlHdjU1L1pBb3U5K3phSGRFZVBYM21YbGhzNndHS2Y0RTdGTGg3aHYyd2Zab2VrVldNYnNpWUFTNi9RdTQ1CmM4djh5UHVFN3paZHlsWHBrL2xEMU5yWnpCaytwanUzZnBhOFJGVjU5SEh1cHlCU0RERUc3SlVDZ1lFQXpZZzUKQ0twbCtYZ291QkllMUVFR08xcXdCcnYxS1JqQWF1ellEUktEYmc4bE5zekY1N3RRbUZTemhsQTNqelllSUVTZwpkSHV1dlQ4NElDc2xqUU14bXRuRE1zZkswdXMyVzcxL28zV3RFWlpSeUpGODUxNndlUW1xa3FxQ2Jzc0ovL2hSCmp4RDlQbTFvcmdHYnVpZ1h6eEpISStpZFAyNmpwdGV5K0NqY05pOENnWUVBeHBKdnBTamtVbnB1YWx4bUxGUjkKQjdaUUtNRGI2TnM1ZDFFSi9EZU9xcDJpM3hvYkdUZTRpV3E1aVkwc0h1ZTNmMFhBNVdzdytHdjZpVnBOeXFlVQoxZjlsWlVtOVVtaFNGZ0pVb3lYWXFXenRObzdJeDV3T2E0SCtFRGFPYzAyRFRraG9YV0RYckc5Y0N2NzZMc2gvCjVTY3E4OWxoSTRQVGd2dW9ScnZ1aXJVQ2dZRUFpTkhVL2NMSkxYL2l3MTQwcmFFM3I4MVgvck9pcVIvei8zbjQKL1FMRkFVQU55dVFZSG9JZ1RiZWM1cDJCenREOHp3aEFOQ3Fka1JlRG1rNStxZGRsYnlybGVXbHN5R21SL3hJdgo1TFdTWjNIRXNackFKaGx2cXJOWG5GanJpU3VhVlk2TlpJcXZ1cDRFb0VrcnpJbWlCOU9vRGV4c3VXeENmdTk2CkVSN0tNVHNDZ1lFQXBxOXhoWEJGK1NFNjRXbGF2RkFxM21VVHlMR1k4Tlc1aUxDemdlTTdhQXJMSXk4eXZIUWgKd1NZQ1U0UDc5MVVLVlIrTGNuRWdYWXErWXhXemRKWU0xdjk3eWlJQnA2V1NzZEc2Q1lVQjR1K1BDZlJFZ3JKdgpoVWdEakhiM25UbWlJNFAzQXc2a1R3T0N0Z1cvck9XL1FvSXpsUGpydzdFYmhwMStvVmE5dHdRPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
addons:
  postgresql: "9.3"
install:
- export GOPATH=/home/travis/gopath
- mv $GOPATH/src/github.com/SpruceHealth $GOPATH/src/github.com/sprucehealth
- cd $GOPATH/src/github.com/sprucehealth/backend
- go get golang.org/x/tools/cmd/vet
- go get golang.org/x/tools/cmd/cover
- sudo apt-get update
- "sudo apt-get remove mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5"
- "sudo apt-get autoremove"
- "sudo apt-get install libaio1"
#- "wget -O mysql-5.6.19.deb http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.19-debian6.0-x86_64.deb"
- "wget -O mysql-5.6.19.deb http://carefront-packages.s3.amazonaws.com/mysql-5.6.19-debian6.0-x86_64.deb"
- "sudo dpkg -i mysql-5.6.19.deb"
- "sudo cp /opt/mysql/server-5.6/support-files/mysql.server /etc/init.d/mysql.server"
- "sudo ln -s /opt/mysql/server-5.6/bin/* /usr/bin/"
# some config values were changed since 5.5
- "sudo sed -i'' 's/table_cache/table_open_cache/' /etc/mysql/my.cnf"
- "sudo sed -i'' 's/log_slow_queries/slow_query_log/' /etc/mysql/my.cnf"
- "sudo sed -i'' 's/basedir[^=]\\+=.*$/basedir = \\/opt\\/mysql\\/server-5.6/' /etc/mysql/my.cnf"
- sudo sed -i'' 's/\[mysqld\]/&\nsql_mode=TRADITIONAL,STRICT_ALL_TABLES,ONLY_FULL_GROUP_BY,PIPES_AS_CONCAT,ANSI_QUOTES\nexplicit_defaults_for_timestamp=1/' /etc/mysql/my.cnf
- "sudo /etc/init.d/mysql.server start"
- "mysqladmin -u root password '12345'"
- "echo \"DELETE FROM mysql.user WHERE User='';\" | mysql -u root -p12345"
- "echo \"flush privileges;\" | mysql -u root -p12345"
- "echo \"CREATE USER 'carefront';\" | mysql -u root -p12345"
- "echo \"GRANT ALL ON *.* TO 'carefront';\" | mysql -u root -p12345"
- rm mysql-5.6.19.deb
# get postgres setup
- sudo pip install --upgrade https://github.com/s3tools/s3cmd/archive/v1.5.0-rc1.tar.gz
- sudo apt-get install python-dateutil
# restore a dump of the diagnosis database to enable searching against diagnosis
# (note this dump includes the entire diagnosis database)
- S3CMD_KEYS="--access_key $DEPLOY_ACCESS_KEY --secret_key $DEPLOY_SECRET_KEY"
- s3cmd $S3CMD_KEYS get s3://spruce-database/diagnosisdb.dump diagnosisdb.dump
- psql -c 'create database travis_ci_test;' -U postgres
- psql -U postgres -d travis_ci_test < diagnosisdb.dump
env:
  matrix:
  - TEST_DB=database_${TRAVIS_BUILD_ID}_${RANDOM}
  global:
  - secure: dupkSyhVUakdRg1vEMjOZ3R5sieB1jTuFN08Q5ImXVpv6+GABxxsiN3OrMhflc70Glb8xZ29BTW3dxOCK9I7AE96p6kNp55++6V+Yz6YIXvJBnAAtNYsaBDOTCM47UYbRHFtzVsvBbnOYcAtopfZ4MoOTdZyKeVXiTSQGrLhM/k=
  - secure: sij+lLl0BS254nnDXy9QjWK7dvmRP1xHD+iZ7Oy+vMqDP/0NAS4uANX7MwT2BjVlVmZ+esMlbWwaBa7QLSMZRSJdcSxmV4wFseZjODzQ2CUOmGfQxAO5ninUHlfG5qyyw5mONrWR+UuiWhB302DrMk3UuNxzOr0ULybaLFCpAhs=
  - secure: r41TDvlA3R2/ajQaaJyGwndvJEQqHB6mbhoaXQJF2S9MgAkkFLzwmvNk1naE11NTxnv2lYRD4Qyqj47AbPp6zhfapzvRshxwK4Ny5mYs3aX8RkRFPFsZanxN7YUhWGq4zoVngIQqE6B5k7lmRxB6fyli4UEJV012PnwuzGJuVxQ=
  - secure: oJ1fs8M1gLOGvCGIIwY6+yRRNwrX05Bv+Gk6mOkxmVwGrlF4mFteN5o3u+CpwV+06Q7Hj5tUCbXQr7gprApSkaZqZmRb4J9861giy38Hmtwtuq5jKdmbpdvfimmEbpycE476kvLf1w0OUxIxyTcA4tpkj8Sr1ZlghPFKqwCHwMI=
  - secure: KbRazbLBuPo64XiscctB1aAtaYd0pfoAQrDXujf7Oy26ngxgGqoRlyZ6LGIjb5wsGe//7MVcU9o6xi5sEGFS1p2cW8JwM8yt6K4apXpXOyaSgi6FsmvgtELThs6o6z6VJIxcV8pd8WTktCX+Rt7JY8Vah2MLbUdnFUPm+JnXNTI=
  # DEPLOY_ACCESS_KEY
  - secure: "YAz1Fjx9e4+tC5p7CV2cpbiQ1kwJG7IDro+n1DI5Qtm66Kco1TLPSFWT+r5O/ccjdtHFK1gYyLg8sE82qRx7uMjp12UgQO+hLyjArq9CEi9JexlFtT3TwpeYSp+JgQpZtobZt23wZ7s4h16X15v/y3Ec9Z9lEr4RogtbSKQ3Vko="
  # DEPLOY_SECRET_KEY
  - secure: "dK/Av/K0zKn4PEpQ9+kV6JkQmgh3h+dYZvm6F9d7/tvjKoZZYkFuPDjgFbN7GETby+XI1flY9+ZMnd54JjxRXDal/yp8lB1qdmuQv0qYyhmkC0++hptBdzeCSxzLyEFjWT9EhRfexrhyIrzmuW6Idt3nJiCg3Xs/KzDhHem9hYA="
  # DIAGNOSIS DB SETUP
  - secure: "gu+jydvG9+m2OpB9uq00Jbs+Jub0yjNvipcvqQGCiznMpIIZmOxV+c2dm7CVmCPCabF0oVJmHlGYFTOsNIWFosGfoTB4Z7f9ielOzgQVDNxqXbPFy07vYlKSSGce3iqob9Gws24/we8wWUenRMmglF7jKMO2EMxmFj5oJvN8Lnc="
  - secure: "AXB5R+3U2B7v2CV3oWK3JKb4xAuw7Wpmnb1sD/FEzo1uiThnGJ6OK9aDkaDwdVrRM5Zz8+ex8BzP1yT6pabq2sXOwdRzegznoa4hMZZI44Fg7U3iu3etyQ7UqUS178dzB979z39ySlqAmckRCerCZS6EZKhVT2q/joPDhBWQ+v0="
  - secure: "ev4sel/Rn+906q1iAA0hRHspSWdzB82NpHH64QBIR6JRGJOAcyD95VDo2SNGuWBy6I7Mcp+ajSP4UksS3uNWipvUrMdOQ2GVSMrUzk4hqMNzpCmesTuTQ4IEbimetViAEZeXgWtPhi7gs35FipoAMmgivfiHIDx46+/kbKK6wPI="
  - secure: "A99SZATPCRsWpxxMoS1e8E6Vwv3LFQHscdAbHESN6KwePzr98uVs/db/hmioTIwT80X1UKfs6Y4h1zHEL8BGa44dLM2y48ceT1GA/GuyAFY/r8rSeh4A/rrpRlBlX3p12ojuXyXuuWLMEdsag09B7lAsY5BGi9/lFMW1+czkjeo="
script:
- export CAREFRONT_PROJECT_DIR=$GOPATH
# Find all directories that contain Go files (all packages). This lets us
# exclude everything under the vendoring directory.
- PKGS=$(find . -name '*.go' | grep -v Godeps | xargs -n 1 dirname | sort | uniq)
- echo $PKGS
- echo $PKGS | xargs go build
- |
  FMT=$(echo $PKGS | xargs go fmt)
  echo $FMT
  [[ -z "$FMT" ]]
# - echo $PKGS | xargs go vet
- echo $PKGS | xargs go test -i -race
- echo $PKGS | xargs -n 1 go test -v -parallel 8 -race

after_success:
- sudo apt-get install python-magic python-dateutil npm
- npm install -g react-tools browserify
- npm install reactify uglifyify
- pushd ./apps/restapi ; ./build.sh ; popd
- mkdir build
- cp ./apps/restapi/restapi build/restapi-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
- bzip2 build/restapi-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
- echo $TRAVIS_COMMIT > build/restapi-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.revision
- S3CMD_KEYS="--access_key $DEPLOY_ACCESS_KEY --secret_key $DEPLOY_SECRET_KEY"
- STATIC_PREFIX="s3://spruce-static/web/$TRAVIS_BUILD_NUMBER"
- s3cmd $S3CMD_KEYS -M --server-side-encryption put build/* s3://spruce-deploy/restapi/
- resources/build.sh
- s3cmd $S3CMD_KEYS --recursive -P -m "text/css" put resources/static/css/* $STATIC_PREFIX/css/
- s3cmd $S3CMD_KEYS --recursive -P -m "application/javascript" put resources/static/js/* $STATIC_PREFIX/js/
#- s3cmd $S3CMD_KEYS --recursive -P -m "application/x-font-opentype" --add-header "Access-Control-Allow-Origin:*" put resources/static/fonts/* $STATIC_PREFIX/fonts/
- s3cmd $S3CMD_KEYS --recursive -P -m "application/application/octet-stream" --add-header "Access-Control-Allow-Origin:*" put resources/static/fonts/*.ttf $STATIC_PREFIX/fonts/
- s3cmd $S3CMD_KEYS --recursive -P -m "application/vnd.ms-fontobject" --add-header "Access-Control-Allow-Origin:*" put resources/static/fonts/*.eot $STATIC_PREFIX/fonts/
- s3cmd $S3CMD_KEYS --recursive -P -m "application/font-woff" --add-header "Access-Control-Allow-Origin:*" put resources/static/fonts/*.woff $STATIC_PREFIX/fonts/
- s3cmd $S3CMD_KEYS --recursive -P -m "application/font-woff2" --add-header "Access-Control-Allow-Origin:*" put resources/static/fonts/*.woff2 $STATIC_PREFIX/fonts/
- s3cmd $S3CMD_KEYS --recursive -P -m "image/svg+xml" --add-header "Access-Control-Allow-Origin:*" put resources/static/fonts/*.svg $STATIC_PREFIX/fonts/
- s3cmd $S3CMD_KEYS --recursive -P -M put resources/static/img/* $STATIC_PREFIX/img/

notifications:
  email:
  - backend@sprucehealth.com
